dist: trusty
sudo: false
notifications:
  email: true
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank

jobs:
  include:
    - stage: build and publish
      language: java
      jdk: openjdk8
      install: skip
      before_script:
        - chmod +x mvnw
      script: ./mvnw clean package
      before_deploy:
        - git config --local user.name "chrisgrollier"
        - git config --local user.email "cgrollier@free.fr"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "target/registry.jar"
        skip_cleanup: true
    - stage: deploy to cf
      language: bash
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P target https://github.com/$GITHUB_USERNAME/msi-registry/releases/download/$RELEASE_TAG/pal-tracker.jar
      before_deploy:
        - echo "Deploying $RELEASE_TAG to Cloud Foundry"
      deploy:
        provider: cloudfoundry
        api: $CF_API_URL
        username: $CF_USERNAME
        password: $CF_PASSWORD
        organization: $CF_ORG
        space: $CF_SPACE
